name: Deploy a Content to Azure Sentinel
on: 
  push:
    branches: [ master ]
#    paths:
#    - 'Detections/**'

jobs:
  deploy-content:
    runs-on: ubuntu-latest
    steps:
                
    # # Authentication
    # - name: Azure Login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.TEMP_CERDENTIALS  }}
    #     environment: 'azurecloud'
    #     enable-AzPSSession: true
     
    # # Checkout
    # - name: Checkout
    #   uses: actions/checkout@v1

    # - name: Read deployment script
    #   id: deploymentScript
    #   uses: juliangruber/read-file-action@v1
    #   with:
    #     path: ./.github/workflows/deploy.ps1
    
    # - name: Run Azure Sentinel powershell script
    #   uses: azure/powershell@v1
    #   with:
    #     inlineScript: ${{ steps.deploymentScript.outputs.content }}

    - name: "Register Dogfood Cloud"
      run:  |
        az cloud register --name Dogfood --endpoint-active-directory-graph-resource-id https://graph.ppe.windows.net/ --endpoint-active-directory-resource-id https://management.core.windows.net/ --endpoint-gallery https://df.gallery.azure-test.net/ --endpoint-resource-manager https://api-dogfood.resources.windows-int.net/ --endpoint-active-directory https://login.windows-ppe.net/

    - name: "Set cloud"
      run:  |
        az cloud set --name Dogfood

    - name: "sign in as sp"
      env:
        SP_ID: ${{ secrets.SP_ID }}
        SP_SECRET: ${{ secrets.SP_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
      run: |
        az login --service-principal -u $env:SP_ID -p $env:SP_SECRET --tenant $env:TENANT_ID

    - name: "sign in as sp"
      run:  |
        az account show
      
      