name: Deploy a Content to Azure Sentinel
on: 
  push:
    branches: [ master ]
    paths:
    - 'Detections/**'

jobs:
  deploy-content:
    runs-on: ubuntu-latest
    steps:
                
    # Authentication
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.TEMP_CERDENTIALS  }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1

    - name: Read deployment script
      id: deploymentScript
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/workflows/deploy.ps1
    
    - name: Run Azure Sentinel powershell script
      uses: azure/powershell@v1
      with:
        inlineScript: ${{ steps.deploymentScript.outputs.content }}