name: Deploy a Content to Azure Sentinel
on: 
  push:
    branches: [ master ]
#    paths:
#    - 'Detections/**'

jobs:
  deploy-content:
    runs-on: ubuntu-latest
    env:
      resourceGroupName: 'newecotestrg2'
      workspaceName: 'cicd-test-la'
      directory: '${{ github.workspace }}/Detections'
      azureCloud: 'Dogfood'
      creds: ${{ secrets.TEMP_CERDENTIALS }}

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      if: ${{ env.azureCloud == 'Prod' }}
      with:
        creds: ${{ secrets.TEMP_CERDENTIALS }}
        enable-AzPSSession: true

####################
### Checkout Step ##
####################

    # Checkout
    - name: Checkout
      uses: actions/checkout@v1

########################
### Deployment Script ##
########################
    - name: Read deployment script
      id: deploymentScript
      uses: juliangruber/read-file-action@v1
      with:
        path: '${{ github.workspace }}/.github/workflows/deploy.ps1'
    
    - name: Deploy Analytic Rules
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        errorActionPreference: 'continue'
        inlineScript: |
          ${{ steps.deploymentScript.outputs.content }}